# Generated by Django 4.1.7 on 2023-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur')], max_length=20, null=True),
        ),
    ]
